//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPBackend.Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SIPBackend.Application.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FailedToRegisterUser {
            get {
                return ResourceManager.GetString("FailedToRegisterUser", resourceCulture);
            }
        }
        
        internal static string FailedToLoginUser {
            get {
                return ResourceManager.GetString("FailedToLoginUser", resourceCulture);
            }
        }
        
        internal static string FailedToChangeInfo {
            get {
                return ResourceManager.GetString("FailedToChangeInfo", resourceCulture);
            }
        }
        
        internal static string FailedToSendMessageWithResettingToken {
            get {
                return ResourceManager.GetString("FailedToSendMessageWithResettingToken", resourceCulture);
            }
        }
        
        internal static string FailedToResetPassword {
            get {
                return ResourceManager.GetString("FailedToResetPassword", resourceCulture);
            }
        }
        
        internal static string FailedToGetAccountInfo {
            get {
                return ResourceManager.GetString("FailedToGetAccountInfo", resourceCulture);
            }
        }
        
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        internal static string PasswordsAreNotEqual {
            get {
                return ResourceManager.GetString("PasswordsAreNotEqual", resourceCulture);
            }
        }
        
        internal static string ModelCreatingIsFailed {
            get {
                return ResourceManager.GetString("ModelCreatingIsFailed", resourceCulture);
            }
        }
        
        internal static string FailedToLogout {
            get {
                return ResourceManager.GetString("FailedToLogout", resourceCulture);
            }
        }
        
        internal static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
        
        internal static string IncorrectCredentials {
            get {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }
        
        internal static string UserAreNotAuthorized {
            get {
                return ResourceManager.GetString("UserAreNotAuthorized", resourceCulture);
            }
        }
        
        internal static string FailedToChangeUserInfo {
            get {
                return ResourceManager.GetString("FailedToChangeUserInfo", resourceCulture);
            }
        }
        
        internal static string TokensAreNotEqual {
            get {
                return ResourceManager.GetString("TokensAreNotEqual", resourceCulture);
            }
        }
        
        internal static string ResettingPasswordTokenIsInvalid {
            get {
                return ResourceManager.GetString("ResettingPasswordTokenIsInvalid", resourceCulture);
            }
        }
        
        internal static string FailedToSendMessage {
            get {
                return ResourceManager.GetString("FailedToSendMessage", resourceCulture);
            }
        }
        
        internal static string FailedToAddNewFriend {
            get {
                return ResourceManager.GetString("FailedToAddNewFriend", resourceCulture);
            }
        }
        
        internal static string FailedToGetFriends {
            get {
                return ResourceManager.GetString("FailedToGetFriends", resourceCulture);
            }
        }
        
        internal static string FailedToDeleteFriend {
            get {
                return ResourceManager.GetString("FailedToDeleteFriend", resourceCulture);
            }
        }
        
        internal static string FailedToFindFriend {
            get {
                return ResourceManager.GetString("FailedToFindFriend", resourceCulture);
            }
        }
        
        internal static string UsersAreAlreadyFriends {
            get {
                return ResourceManager.GetString("UsersAreAlreadyFriends", resourceCulture);
            }
        }
        
        internal static string UsersAreNotFriends {
            get {
                return ResourceManager.GetString("UsersAreNotFriends", resourceCulture);
            }
        }
        
        internal static string FailedToAcceptRequest {
            get {
                return ResourceManager.GetString("FailedToAcceptRequest", resourceCulture);
            }
        }
        
        internal static string FailedToGetAllUsersWithRequests {
            get {
                return ResourceManager.GetString("FailedToGetAllUsersWithRequests", resourceCulture);
            }
        }
        
        internal static string FailedToGetUserInfo {
            get {
                return ResourceManager.GetString("FailedToGetUserInfo", resourceCulture);
            }
        }
        
        internal static string FailedToGetRefreshToken {
            get {
                return ResourceManager.GetString("FailedToGetRefreshToken", resourceCulture);
            }
        }
        
        internal static string FailedToGetAllMessages {
            get {
                return ResourceManager.GetString("FailedToGetAllMessages", resourceCulture);
            }
        }
        
        internal static string GettingChatInfoIsFailed {
            get {
                return ResourceManager.GetString("GettingChatInfoIsFailed", resourceCulture);
            }
        }
        
        internal static string ChatDoesNotExist {
            get {
                return ResourceManager.GetString("ChatDoesNotExist", resourceCulture);
            }
        }
        
        internal static string TheseChatParticipantsDoNotExist {
            get {
                return ResourceManager.GetString("TheseChatParticipantsDoNotExist", resourceCulture);
            }
        }
    }
}
