//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPBackend.DAL.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SuccessMessage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SIPBackend.Application.Resources.SuccessMessage", typeof(SuccessMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LogoutIsSucceed {
            get {
                return ResourceManager.GetString("LogoutIsSucceed", resourceCulture);
            }
        }
        
        internal static string AccountHasReachedSuccessfully {
            get {
                return ResourceManager.GetString("AccountHasReachedSuccessfully", resourceCulture);
            }
        }
        
        internal static string UserInfoIsChangedSuccessfully {
            get {
                return ResourceManager.GetString("UserInfoIsChangedSuccessfully", resourceCulture);
            }
        }
        
        internal static string ResettingPasswordTokenIsActivated {
            get {
                return ResourceManager.GetString("ResettingPasswordTokenIsActivated", resourceCulture);
            }
        }
        
        internal static string MessageWasSentSuccessfully {
            get {
                return ResourceManager.GetString("MessageWasSentSuccessfully", resourceCulture);
            }
        }
        
        internal static string SendingResettingPasswordTokenIsSuccessful {
            get {
                return ResourceManager.GetString("SendingResettingPasswordTokenIsSuccessful", resourceCulture);
            }
        }
        
        internal static string FriendAddedSuccessfully {
            get {
                return ResourceManager.GetString("FriendAddedSuccessfully", resourceCulture);
            }
        }
        
        internal static string GettingFriendsIsSuccessful {
            get {
                return ResourceManager.GetString("GettingFriendsIsSuccessful", resourceCulture);
            }
        }
        
        internal static string DeletingFriendIsSuccessful {
            get {
                return ResourceManager.GetString("DeletingFriendIsSuccessful", resourceCulture);
            }
        }
        
        internal static string FindingFriendIsSuccessful {
            get {
                return ResourceManager.GetString("FindingFriendIsSuccessful", resourceCulture);
            }
        }
        
        internal static string FriendsRequestApproved {
            get {
                return ResourceManager.GetString("FriendsRequestApproved", resourceCulture);
            }
        }
        
        internal static string GettingAllUsersWithRequests {
            get {
                return ResourceManager.GetString("GettingAllUsersWithRequests", resourceCulture);
            }
        }
        
        internal static string RefreshTokenGotSuccessfully {
            get {
                return ResourceManager.GetString("RefreshTokenGotSuccessfully", resourceCulture);
            }
        }
        
        internal static string GettingAllMessagesIsSuccessfull {
            get {
                return ResourceManager.GetString("GettingAllMessagesIsSuccessfull", resourceCulture);
            }
        }
        
        internal static string GettingChatInfoIsSuccessful {
            get {
                return ResourceManager.GetString("GettingChatInfoIsSuccessful", resourceCulture);
            }
        }
    }
}
